openapi: 3.0.3
info:
  title: Email Communication Service API
  version: 1.2.0
  description: API for sending emails, including attachments via multipart/form-data, with CC, BCC, and selecting an SMTP service based on MarketParticipant ID.
servers:
  - url: /api/v1

paths:
  /emails/send:
    post:
      summary: Send an email with attachments
      description: Sends an email with optional attachments, CC, and BCC fields. Connects to the appropriate SMTP service based on the MarketParticipant ID.
      tags:
        - Email
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                to:
                  type: array
                  description: list of recipient email addresses
                  items:
                    type: string
                    format: email
                cc:
                  type: array
                  description: list of CC email addresses (optional)
                  items:
                    type: string
                    format: email
                bcc:
                  type: array
                  description: list of BCC email addresses (optional)
                  items:
                    type: string
                    format: email
                from:
                  type: string
                  format: email
                  description: Email address of the sender
                subject:
                  type: string
                  description: Subject of the email
                  example: "Welcome to our service"
                body:
                  type: string
                  description: Body content of the email
                  example: "Thank you for signing up."
                marketParticipantId:
                  type: string
                  description: Identifier to select the SMTP service
                  example: "MPID-12345"
                attachments:
                  type: array
                  description: Send  mulitple file attachments
                  items:
                    type: string
                    format: binary
      responses:
        '200':
          description: Email sent successfully
        '400':
          description: Invalid input
        '500':
          description: Error occurred while sending email