name: OpenAPI Generator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-api:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java environment (needed to run the JAR file)
    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    # Download OpenAPI Generator JAR
    - name: Download OpenAPI Generator JAR
      run: wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.0.0/openapi-generator-cli-7.0.0.jar -O openapi-generator-cli.jar

    # Run the OpenAPI Generator with parameters
    - name: Generate API client
      run: |
        java -jar openapi-generator-cli.jar generate \
          -i https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml \
          -g java \
          -o ./generated

    # (Optional) Upload generated API to GitHub as an artifact
    - name: Upload Generated API
      uses: actions/upload-artifact@v3
      with:
        name: generated-api
        path: ./generated
