name: Tag Repo from OpenAPI Version

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (adjust branch as needed)
  workflow_dispatch:  # Allow manual triggering

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Parse the version from the OpenAPI file
      - name: Extract version from OpenAPI
        id: extract_version
        run: |
          # Adjust this path to your OpenAPI file
          OPENAPI_FILE="openapi.yml"
          
          # Extract the version using yq (a lightweight YAML processor)
          VERSION=$(yq '.info.version' $OPENAPI_FILE)

          # Make sure the version was found
          if [ -z "$VERSION" ]; then
            echo "Version not found in OpenAPI spec!"
            exit 1
          fi

          # Print the extracted version
          echo "Version found: $VERSION"

          # Set the version as an output
          echo "::set-output name=VERSION::$VERSION"

      # Create a new Git tag and push it
      - name: Tag the repo
        run: |
          VERSION=${{ steps.extract_version.outputs.VERSION }}
          
          # Check if this tag already exists
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag v$VERSION already exists"
            echo "Either update the Open API Spec version or remove the version tag from the repo"
            exit 1
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            # Create and push the new tag
            git tag "v$VERSION"
            git push origin "v$VERSION"
          fi

